### ISSUE TITLE
ReadAllEventsFromStream crashes when attempting to read hard-deleted stream

### ISSUE THREAD

**Issue by iblazhko** [BullOak/BullOak#112]
Description
---

When trying to read a stream that has been hard-deleted, `ReadAllEventsFromStream` fails with following error:

```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at BullOak.Repositories.EventStore.EventStoreSession`1.ReadAllEventsFromStream()
   at BullOak.Repositories.EventStore.EventStoreSession`1.Initialize()
   at BullOak.Repositories.EventStore.EventStoreRepository`2.BeginSessionFor(TId id, Boolean throwIfNotExists)
```

## Steps to reproduce

1. Create a stream
2. Hard-delete a stream using `IEventStoreConnection`: `await connection.DeleteStreamAsync(streamId, -1, true)`
3. Try to start BullOak session for that stream (`BeginSessionFor(streamId, false)`)
4. BANG!

**Comment by skleanthous** [comment]
@iblazhko is this with the new EventStore server? I added integration tests for this and I couldn't reproduce this.

**Comment by skleanthous** [comment]
Hm, I couldn't reproduce this against 5.0 either. I will continue to try to reproduce this, but I would appreciate some more input on this.

**Comment by skleanthous** [comment]
@iblazhko I initially thought you were deleting through BullOak EventStore lib, but then I saw you manually hard-deleted.

I fixed that in above PR, but bear in mind that BO using naming from EventStore, only does soft deletes. This means that the events are deleted, but the stream is open for writing.
