### ISSUE TITLE
BO-60: Add the ability to specify custom initalisers for state types

### ISSUE THREAD

**Issue by ninjaboy** [BullOak/BullOak#60]
Description
---

There's currently no way to customise the default values for a newly created state object when using interfaces to hold state.
Such functionality may be needed to configure the default values for the newly created state object.

Proposal
---

The ability to configure custom initialiser types should be introduced by BullOak similar to the Appliers concept

``` C#
public class public HoldSomeStateInitializer : ICanInitialize<IHoldSomeState>
{
       public IHoldSomeState Initialise(IHoldSomeState fresh)
      {
           fresh.InitialState = true;
           fresh.Value = 1000;
      }
}
//registered via
builder.Register(_ => Configuration.Begin()
                .WithDefaultCollection()
                .WithDefaultStateFactory()
                .WithAnyAppliersFrom(Assembly.GetAssembly(typeof(IHoldSomeState)))
                .AndNoMoreAppliers()
                .WithNoUpconverters()
                //The below needs to be supported
                .WithInitializersFrom(Assembly.GetAssembly(typeof(HoldSomeStateInitializer)))
                //Or optionally
                .WithInitializer<HoldSomeStateInitializer>()
               //Not sure if below is needed
               .AndNoMoreInitializers()
                .Build())
                .As<IHoldAllConfiguration>();

//or optionally delcaratively
[Intializer(typeof(HoldSomeStateInitializer))] //Initialiser for type
public interface IHoldSomeState {
  int Value {get;set;}
  [InitialState(false)]  //optionally declaratively on field by field basis
  bool InitialState{get;set;}
}

//And behaving as:
using (var session = ordersRepository.BeginSessionFor(orderId))
{
  var state = session.GetCurrentState();
  Assert.Equals(state.InitialState, true );
  Assert.Equals(state.Value, 1000);
}
```

Benefits
---

1. The ability to support initial state for the state types

Risks
---
No obvious risks identified

**Comment by skleanthous** [comment]
## Initializers through setup:
**Pros**:
- Easy to discover

**Cons**:
- Breaking change in API

## Declarative initializers \ Attribute initializers

**Pros**:
- Non-breaking change in API
- Readable
- Unobtrusive, in the case of `DefaultValueAttribute` on properties themselves

**Cons**:
- Difficult to discover (only by reading documentation)
- More complicated to develop & maintain
- Makes loading times longer
- `DefaultValueAttribute` is very limited in its capabilities

**Comment by skleanthous** [comment]
However, considering the above, I have to say that:
- These are meant to be used on types that represent _state_. As such, we expect these types to not have dependencies, and them having dependencies (in almost all cases) is actually an antipattern.
- It is very natural in event sourced solutions to have an empty state and initialization happens through an event (either fired from ctor or replayed through reconstitution). This breaks that pattern and also considering that this functionality allows to alter the state objects outside of what is described in events, this very obviously allows for very serious bugs and\or mistakes to happen.

I think, while this request seems very powerful, we would benefit more if we focused on the need that resulted in this. Specifically in this case is the need to know if a state that was returned from session is a new one or if it was loaded from existing events in the stream. cc @ninjaboy

**Comment by skleanthous** [comment]
The more I think about this, the more I think that while it is a power tool, this library is opinionated in a way that it won't let users shoot themselves in the foot. Because of this and that this feature would allow you to introduce breaking changes in the semantics of the events in the event stream simply by changing code in the initializer, I will be closing this request and opening a new one about providing information whether a stream is a new one or not, which is a piece of information which arises from a valid need (it answers the question if the stream existed already or not) plus it cannot be abused.
