### ISSUE TITLE
BO-88: Consolidate target platforms

### ISSUE THREAD

**Issue by iblazhko** [BullOak/BullOak#88]
Description
---

At the moment of writing there are following target platforms used in the BullOak:

* .NET Core projects
  - `net462`
  - `net451`
  - `net47`
  - `netcoreapp2.0`
* .NET Framework projects
  - `v4.5.2`
  - `v4.6.1`
  - `v4.7`

On a reasonably clean PC where only .NET Core SDK, .NET Framework 4.7 and 4.6 SDK are installed (with dev packs), but no Visual Studio, BullOak does not build because of missing target platforms.

Proposal
---

Use following target platform conventions:

* .NET Core projects
  - `netstandard2.0` - use this by default in libraries (e.g. `BullOak.Repositories`). These can be consumed from both .NET Core and .NET Framework projects
  - `netcoreapp2.0` - use this in .NET Core command-line tools and test projects (test projects needs to use `netcoreapp2.0`, not `netstandard2.0`, which is required by test runners, as I understand)
  - `net461` (or `net462`) - use this only when explicitly required by dependencies (like in repositories implementation)
* .NET Framework projects
  - `v4.6.1` - consolidate all projects to use `v4.6.1`

Ideally it would be better to move all the projects to .NET Core, but unfortunately SpecFlow is not .NET Core-friendly just yet.

Benefits
---

1. More consistent codebase
1. Less dependencies to install on a maintainer's PC or a build agent

Risks
---

N/A

Subtasks
---

- [ ] Use `System.Reflection.Emit` nuget to emit classes for state and events.
- [ ] Change `BullOak.Repositories` to target `netstandard2.0` and remove all other targets

**Comment by skleanthous** [comment]
@iblazhko `netstandard2.0` is not an option because it does not allow ILEmit.

**Comment by skleanthous** [comment]
@iblazhko I didn't notice that there are `System.Reflection.Emit` packages in nuget for netstandard :) I'll schedule this for ASAP.
