### ISSUE TITLE
BO-9: Create full end-to-end tests

### ISSUE THREAD

**Issue by skleanthous** [BullOak/BullOak#9]
Description
---
The approach we have taken so far was to use unit tests to test the individual parts of BullOak, but complex and distributed systems fail in complex ways. As such, we need to have assurance that the system as a whole works as promised offering the guarantees we need. While its not feasible (at least at first) to create all the different permutations of infrastructure that we use for tests, but we should aim to provide tests that test the different behaviours and factors contributing to complexity.

This issue is to create the basic, happy path tests. These are to serve as a beginning to help drive development, and we will slowly add more tests (as we add more features) to exercise all different situations we are interested to test?

Proposal
---
We need to check all the different factors that contribute to the complexity of the system and ideally some combinations of these factors. Eventually we want to do:
1. Persistence: 
   1. [x] i. Event sourced 
   1. [x] ii. Entity persistence
### Will reschedule below:

~2. Communication~
~i. Messaging\asynchronous (out of order, delayed)~
~ii. Synchronous\remote (can fail)~
~iii. Synchronous\local~

Benefits
---
1. It can serve as documentation to the system
1. It can serve as a learning tool to newcomers to distributed system design
1. It can help us during development of new features
1. It can serve as a template until we actually do a template

Risks
---
1. There are a lot of possible permutations, which can cause this feature to take a long time to finish
1. We miss some of the properties that should be considered which could lessen the value we provide with this feature

**Comment by sagarSahay** [comment]
So this issue looks very similar to implementing acceptance tests (for happy path ) but for the infrastructure projects, is that right?

**Comment by skleanthous** [comment]
Yes, exactly.
